name: Report Size Deltas

on:
  schedule:
    # schedule action for every five minutes (ends up being a little longer in practice)
    - cron: "*/5 * * * *"

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/actions/libraries/report-size-deltas@master
