name: Spell Check

on: [push, pull_request]

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Spell check
        uses: arduino/actions/libraries/spell-check@master
        with:
          ignore-words-list: extras/codespell-ignore-words-list.txt
          skip-paths: ./extras/TrustAnchors,./src/bearssl
